### PR TITLE
Add promise based model call

### PR DESCRIPTION
**Pull request by ahsang**
I feel that this needs to be done in all the docs with thenable objects. Helps newbies start in the right direction as I feel it is much easier to control code with promises

### CODE REVIEW

**Comment by sgress454** [comment]
Hi @ahsang, fair enough.  I'll merge but it needs a little cleanup: the heading "Using promises" shouldn't have code styling (i.e. lose the backticks), and you forgot a closing ``` to end the code example block!

**Comment by ahsang** [comment]
@sgress454 made the changes. Sorry for the delay, the notification got lost. If you think i can help more, i will go through the docs and add promise based examples for all the functions?
I think that would really help newbies improve the general quality of starter code

**Comment by ahsang** [comment]
@sgress454 can you please respond?

**Comment by sgress454** [comment]
Sorry for the delay.  It seems that instead of removing the backticks around `using promises`, you removed the heading (the `###`).  Please remove the backticks and replace the heading, so that it looks like this in the raw markdown file:

```
### Using Promises
```

I wouldn't go adding promises to every function call in the docs.  Nothing against them, but it's twice as much documentation to maintain, and internally we don't use them at all so any time we added to / updated the docs it'd be unlikely that we'd remember to put in a promises version.  We might end up moving this to a separate "using promises" page under "models" so that it gets its own link, that way it'd be more prominent and make it clear that any method in the ORM can be called using promises.

**Comment by ahsang** [comment]
@sgress454 done. I can help write up the using promises page if you want.

**Comment by sgress454** [comment]
Awesome, thanks @ahsang!

**Pull request merged**
