### PR TITLE
[proposal] Suggested example for new versions of winston

### PR DESCRIPTION
**Pull request by luislobo**
The example on how to integrate Winston is for an old version of it.

Suggested is an example that works pretty well for me.

### CODE REVIEW

**Comment by luislobo** [comment]
@johnabrams7 Related to https://github.com/balderdashy/sails/issues/4601

**Comment by madisonhicks** [comment]
Hey, @luislobo! 
I just tried this example in a new Sails app with the latest versions of Sails, winston, and captains-log, and I'm getting this error: 

`TypeError: Cannot destructure property `combine` of 'undefined' or 'null'.`

Any thoughts on where this is coming from?

**Comment by luislobo** [comment]
@madisonhicks Hey, sorry I missed this one. I'll give it a check

**Comment by mikermcneil** [comment]
Thanks @luislobo!

**Pull request merged**
