### PR TITLE
Update res.redirect.md (statusCode)

### PR DESCRIPTION
**Pull request by Guillaume-Duval**
I use this method with the 'statusCode' parameter to correct 404 errors (for example).
I hope this information could help some.

### CODE REVIEW

**Comment by Guillaume-Duval** [comment]
If you want me to modify or correct the texts, no worries, just tell me.
(English is not my mother tongue ^^)

**Comment by rachaelshaw** [comment]
@Guillaume-Duval I just talked to @mikermcneil about this, and while the `statusCode` parameter technically works, the recommended way of including a status code is using` res.status().redirect()`, e.g.:
```javascript
return res.status(301).redirect('/foo');
```
If you have a moment to add a note to [this page in the 1.0 docs](https://github.com/balderdashy/sails-docs/blob/1.0/reference/res/res.redirect.md) mentioning using `res.status()` to include a status code, that would be great -- we'd just rather not add the `statusCode` parameter to this table since it's been deprecated in express.

Thank you!

**Comment by Guillaume-Duval** [comment]
Sorry for my late response.

I removed my additions on the optional parameter "statusCode" and added a note about the example with the chained functions as requested.

Thank you

**Comment by rachaelshaw** [comment]
@Guillaume-Duval thank you! Looks good to merge in now.

**Comment by oshatrk** [comment]
@rachaelshaw, there is no plans to deprecate Express' `res.redirect(status, url)` nor in [its documentation](http://expressjs.com/en/4x/api.html#res.redirect), nor in [its source code](https://github.com/expressjs/express/blob/67168fe231445a82dc1e8dde6a93ee9441be28c1/lib/response.js#L863-L907).
They only deprecate [use of status code as a second parameter](https://github.com/expressjs/express/blob/67168fe231445a82dc1e8dde6a93ee9441be28c1/lib/response.js#L874):
```
deprecate('res.redirect(url, status): Use res.redirect(status, url) instead');
```

Even more, the code suggested by Sails documentation
```
return res.status(301).redirect('/foo');
```
doesn't work with Express' `res.redirect()` at all. And so it doesn't work for any HTTP requests in any Sails application [as they hit Express' router](https://github.com/balderdashy/sails/blob/master/lib/router/README.md#faq).
This code works only in particular case when one redirects SocketIO requests.

So @Guillaume-Duval is completely right and his initial commit shoud get a gold.

**Comment by mikermcneil** [comment]
@oshatrk you are so right, thanks.  Looking into resolving this for Sails v1.

**Comment by mikermcneil** [comment]
@oshatrk @Guillaume-Duval https://github.com/Guillaume-Duval/sails-docs/pull/1

**Pull request merged**
