### PR TITLE
Add documentation for how to use Coffeescript in sails projects

### PR DESCRIPTION
**Pull request by leosuncin**
Describe how to use Coffeescript in sails, also help to solve https://github.com/balderdashy/sails/issues/3479 and future related questions

### CODE REVIEW

**Comment by leosuncin** [comment]
Please @mikermcneil check if have any error i'm not a native english speaker

**Comment by mikermcneil** [comment]
> Please @mikermcneil check if have any error i'm not a native english speaker

Hey, you did well!  I just added some comments inline.  In most cases, I couldn't tell you exactly _why_ some things sound right or wrong (blame it on the crazy forefathers of the English language :p), but I did try to add bullet points of what I changed in case it's helpful for you.  I always wish people would do that for me when I'm trying to speak their language :)

Thanks a bunch!

**Comment by leosuncin** [comment]
Thanks @mikermcneil for the observations.

**Comment by mikermcneil** [comment]
Great work @leosuncin.

**Pull request merged**
