### PR TITLE
Update res.redirect.md

### PR DESCRIPTION
**Pull request by tswayne**
* Chaining res.status with res.redirect no longer works.

### CODE REVIEW

**Comment by sgress454** [comment]
Good catch, @tswayne !

**Comment by mikermcneil** [comment]
@tswayne Thanks!  Would you mind resubmitting this on the 1.0 branch?

**Comment by mikermcneil** [comment]
@tswayne Also, just to be sure:  This is not working even when you use `res.status()` to set a redirect-compatible status code, such as 301?

https://trello.com/c/CUAdrA5b

**Comment by tswayne** [comment]
@mikermcneil yes that is correct.  Will do.

**Comment by tswayne** [comment]
@mikermcneil the 1.0 docs for res.redirect are already correct.

**Pull request merged**
