### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by anibalmf1**

### CODE REVIEW

**Comment by brettimus** [comment]
again, obridago!

and again, paging @marceloboeira and @gabrielalmir10 !

**Comment by brettimus** [comment]
@marceloboeira, can you give this a 👍 too? my protuguese is really really really bad 😁

**Comment by marceloboeira** [comment]
@brettimus of course. 

@anibalmf1 once again, thanks!

**Comment by brettimus** [comment]
boom bam 🎉

**Pull request merged**
