### PR TITLE
sails.config.csrf.routesDisabled support RegExp and express-style path

### PR DESCRIPTION
**Pull request by bolasblack**
see https://github.com/balderdashy/sails/pull/3661

### CODE REVIEW

**Comment by brettimus** [comment]
@bolasblack Sorry this has been open for so long! Are we waiting for your PR to be merged on sails proper?

**Comment by bolasblack** [comment]
@brettimus Yes, I think 😂

**Comment by brettimus** [comment]
Right on. We'll keep flying a holding pattern till then ✈️ ☁️

**Comment by bolasblack** [comment]
:) Thank you

**Comment by brettimus** [comment]
Looks like @sgress454 covered this in 4440b08. Closing! Thanks for your contribution, @bolasblack

**Pull request closed without merging**
