### PR TITLE
Add French translation repo

### PR DESCRIPTION
**Pull request by marrouchi**
Hi,

I've started today on working it https://github.com/marrouchi/sails-docs-fr

### CODE REVIEW

**Comment by rachaelshaw** [comment]
@marrouchi awesome! Thanks for starting on a new translation

**Comment by rachaelshaw** [comment]
@marrouchi just so you're aware: we're planning on releasing Sails v1.0 later this month, and when that happens, the content for the 1.0 docs will be moved onto the master branch of this repo. Luckily, most of the major changes should be to the Reference section, which I noticed you haven't started translating yet. To get an idea of the pages that are being changed significantly, I recommend keeping an eye on the [1.0 branch](https://github.com/balderdashy/sails-docs/tree/1.0). The [1.0 upgrade guide](https://github.com/balderdashy/sails-docs/blob/1.0/upgrading/To1.0.md) also has a lot of information about what's changing, but it's still a work-in-progress.

Thanks for all your work so far! Hopefully the upcoming release doesn't cause too much trouble with the translation project.

**Comment by marrouchi** [comment]
@rachaelshaw Thank you for notifying me. I'll keep an eye on the 1.0 branch :+1: 

Will the documentation be accessed by version in the official website ? Or will there be only for Sails 1.0 ?

**Comment by rachaelshaw** [comment]
It'll show the 1.0 docs on the main website, and the 0.12 docs will be compiled onto 0.12.sailsjs.com. (We'll probably keep the same version dropdown that's on the website now for getting to the 0.12 docs easily)

**Comment by marrouchi** [comment]
Okay !

**Pull request merged**
