### PR TITLE
Update Policies.md

### PR DESCRIPTION
**Pull request by tjwebb**
- implements balderdashy/www.sailsjs.org#63

### CODE REVIEW

**Comment by jub3i** [comment]
Hi @tjwebb Thanks for the PR! I want to merge this but I am hesitant to remove the link to geektantra. I have not used passport but I skimmed over the blog post and all the code seems compatible with sails v0.11, and explains in depth how everything works. If you update your PR to include the geektantra link (perhaps after) the npm links, I'll merge, unless you have any other comment.

**Comment by tjwebb** [comment]
Ok sounds good. I am wary about walkthroughs from 2013 but if it still
works, then that's ok with me.

**Comment by jub3i** [comment]
I was hoping you could confirm if the code was still working since I'm not experienced with passport :) But if neither of us can confirm or deny that the code is out of date, I think its best we should leave it in - but put your newer stuff above it. Update your branch and I'll merge!

**Comment by jub3i** [comment]
@tjwebb Just noticed on Line 168 of your PR the link text says `sails-auth-generator` but the npm module is `sails-generate-auth`

**Comment by tjwebb** [comment]
@jub3i updated

**Comment by jub3i** [comment]
@tjwebb thanks!

**Pull request merged**
