### PR TITLE
add accurate description of node.js

### PR DESCRIPTION
**Pull request by joaostein**
Hey all,

Tried to be more accurate describing node, since we already have an in-depth one above.  also removed some trailing whitespace.

### CODE REVIEW

**Comment by rachaelshaw** [comment]
@joaostein looks like there's a word missing in the new description (Right now it says: "Node.js allows to run"). Once you update it, I can merge this in. Thank you!

**Comment by joaostein** [comment]
Hey @rachaelshaw, it's not 100% clear which word is missing.

Something in the lines of: 

*"More simply put, Node.js allows to quickly and efficiently run JavaScript code outside the browser, making it possible to use the same language on both the frontend and the backend"* would be more meaningful to me, how does it sound to you? any suggestions?

**Comment by brettimus** [comment]
@joaostein i believe @rachaelshaw wanted you to put a pronoun in there

> More simply put, Node.js allows us to quickly and efficiently run JavaScript code outside the browser, making it possible to use the same language on both the frontend and the backend

**Comment by joaostein** [comment]
thanks @brettimus, added the fix :)

**Comment by brettimus** [comment]
woohoo! merging. what time is it? merge time! :tada:

**Comment by joaostein** [comment]
awesome!! thanks to both of you :)

**Pull request merged**
