### PR TITLE
Say goodbye to Timothy the monkey.

### LINKED ISSUE #400: Must know about Timothy the Monkey
In the file `concepts/ORM/Models.md` (currently line 91) you link to an incident involving Timothy the Monkey, but the link is empty.

What is so special about this monkey? I need closure!

### PR DESCRIPTION
**Pull request by brettimus**
Closes #400 

## Straightforward Explanation
I'd like someone else to give the :+1: to removing Timothy from the docs.

## Dramatic Explanation
Listen. I haven't made this decision lightly.

My father's name is Timothy. My middle name is Timothy. I am also a vegetarian. 

Hence, removing Timothy the Monkey from the docs carries an emotional weight for me that this PR can only begin to capture. 

I'm apt to wonder if I'm making a good decision. 

So, I'd ask that another collaborator merge these changes. I just... I just can't. It's too much. :see_no_evil:

### CODE REVIEW

**Comment by rachaelshaw** [comment]
@mikermcneil leaving this one up to you. I can't.

**Comment by phishy** [comment]
Keep it. Why remove it? :-)

**Comment by brettimus** [comment]
Because if you love something you'll let it go! :sob:

**Comment by brettimus** [comment]
Oh shoot I am a huge dumb today and pushed unrelated work to this branch. Blech. I'll just close it. 

Timothy lives to see another day!

**Comment by rachaelshaw** [comment]
The fates have spoken!

**Pull request closed without merging**
