### PR TITLE
Translated: i18n, ORM, Security, Services,Testing and Views

### PR DESCRIPTION
**Pull request by hiroto-y**
Hi, guys, I'm back! Since I got some time to work on, I finished translate some part of concepts section.
We have Upgrading, Sessions, and Extend Sails left but I will finish it in a few days.

### CODE REVIEW

**Comment by hiroto-y** [comment]
Also finished with Extending Sails, Upgrading and Sessions. The only things left now is concepts/Upgrading/To0.10.md .

**Comment by hiroto-y** [comment]
Hi, could someone merge this pull request? I don't have write access privilege.

**Comment by sgress454** [comment]
Thanks @hiroto-y, really appreciate it!

**Comment by hiroto-y** [comment]
You’re welcome. I'll send another pull request when I finish another part.

**Pull request merged**
