### PR TITLE
Japanese edition of Sails documentation

### PR DESCRIPTION
**Pull request by hiroto-y**
I'm Kory, a JavaScript engineer based in Tokyo.
I translated the Sails concept document into Japanese.

### CODE REVIEW

**Comment by hiroto-y** [comment]
Sorry for made you so long. I guess I finished merge conflicts.

**Comment by hiroto-y** [comment]
Also, added newly translated section.

**Comment by irlnathan** [comment]
@hiroto-y Thank you so much!

**Comment by mikermcneil** [comment]
@hiroto-y awesome!

**Comment by irlnathan** [comment]
@hiroto-y  I also added you as a contributor to the Japanese Translation Team.

**Comment by mikermcneil** [comment]
Hey @hiroto-y, would you send a note to support@treeline.io with your email address?  A friend in Japan asked for an introduction re: the Sails.js community in Japan.

**Pull request merged**
