### PR TITLE
Fix hook spec links

### PR DESCRIPTION
**Pull request by IanVS**
Fixing a few broken links I came across.

### CODE REVIEW

**Comment by IanVS** [comment]
There are actually more of these, but I don't understand the following behavior:

http://sailsjs.org/documentation/concepts/extending-sails/Hooks/hookspec/defaults.html -> works
http://sailsjs.org/documentation/concepts/extending-sails/Hooks/hookspec/                      -> broken

What's the best way to fix these links?

**Comment by jledentu** [comment]
The correct URL is http://sailsjs.org/documentation/concepts/extending-sails/hooks/hook-specification.

I can't find where the hookspec -> hook-specification mapping is handled. 302 redirections are done on other hookspec pages, but not on the hookspec root. If the `hook-specification` is the definitive path, then we should replace all `hookspec` occurences.

**Comment by rachaelshaw** [comment]
The old links were (for the most part) the same as the path to where its file is in `sails-docs`, so we're currently checking for old links we can redirect using the template paths in the [menu file](https://github.com/balderdashy/www.sailsjs.org/blob/master/views/partials/doc-menus/concepts.jsmenu) that the doc-templater creates.
I think the problem with http://sailsjs.org/documentation/concepts/extending-sails/Hooks/hookspec/ is because it's for an overview page, and so the link doesn't completely match a file path. I'll try it with some other old overview page links to see if this is something I need to fix in the sailsjs.org project, or if that link was just broken to begin with.

**Comment by rachaelshaw** [comment]
@IanVS thanks for fixing this. Redirecting old links is a temporary measure (that apparently doesn't always work) so updates to the newer links are incredibly helpful in the long term.

**Pull request merged**
