### PR TITLE
Updating the docs for Remove From Collection

### PR DESCRIPTION
**Pull request by jodonnell-broadsoft**
@mikermcneil Is this what you had in mind for a more complete example? I'm open to any guidance to help you better :)

### CODE REVIEW

**Comment by mikermcneil** [comment]
@jodonnell-broadsoft This looks great, thanks!  A few small things would be helpful:

• While you're in there, feel free to rip out the "uniqueID" docmeta tag at the bottom of the files (we added those a long time ago, but they are totally unnecessary now and also not actually unique anymore x_x).  The "displayName" however is super important- it's used to determine the "title" of the doc page for search engine traffic / browser tab, and is also used to generate the URL slug (so we have to be careful not to change them or risk breaking permalinks).
• Would you set up a table of parameters like http://sailsjs.org/documentation/reference/blueprint-api/find-one#?parameters
  • I figure we leave out ":model" from the params to avoid confusion, but include everything else-- so in this case "record", "association", and "record_to_remove" (let's change that to "recordToRemove")-- in fact any time you see snake case like that for a variable/parameter/property name, feel free to change it to camel-case (it's always preferred) , and there's no special intent behind the camel-case; it's only there because we've had a lot of different eyeballs and hands on the docs over the years and we hadn't established the convention early on.

**Comment by jodonnell-broadsoft** [comment]
@mikermcneil SAILS WORK ON CHRISTMAS MORNING!?! Get back to the egg nog and have a sit by the tree! 

:)

Thanks for the feedback. I really appreciate it. Will update this PR when I get a chance today. Merry Christmas :christmas_tree:

**Comment by jodonnell-broadsoft** [comment]
@mikermcneil That should make it more in line with the other docs. Let me know if you want anything else changed. I'll add another PR for getting rid of all the unused unique IDs in the repo :)

**Comment by mikermcneil** [comment]
@jodonnell-broadsoft haha :christmas_tree: gotta take it when you can get it.  Merry Christmas to you too (a little late) but happy new year at least :)

This looks great, digging the use of personification :+1:   Whatever will Dolly do next? :8ball:

**Comment by jodonnell-broadsoft** [comment]
@mikermcneil more stories about her will be told!

**Pull request merged**
