### PR TITLE
Update bootstrap.test.js

### PR DESCRIPTION
**Pull request by hungle88**
Update sails.lift callback parameter from `server` to `sails`

### CODE REVIEW

**Comment by rachaelshaw** [comment]
@hungle88 your change is definitely better than what was there, but for clarity's sake it would actually be best to remove the `sails` argument altogether, since it is already accessible without passing it through. Mind making that change before I merge this?

**Comment by hungle88** [comment]
@rachaelshaw: Actually I was wondering the same thing too. Fixing it now!

**Comment by hungle88** [comment]
@rachaelshaw Done!

**Comment by rachaelshaw** [comment]
@hungle88 thank you! Looks good

**Pull request merged**
