### PR TITLE
Create req.headers.md

### PR DESCRIPTION
**Pull request by takirohit**
add some example for accessing the req.headers

### CODE REVIEW

**Comment by jub3i** [comment]
@takirohit If you go look at the other files in ./reference/req/ you'll see that they have the same structure. Your commit is missing the heading and introduction parts of the structure. If you add in the missing parts I'll merge :)

**Comment by takirohit** [comment]
@jub3i  I need to change the commit message or need to add more details to the doc.

**Comment by takirohit** [comment]
@jub3i  Thanks for guiding, Now I think, I have added the missing part, If something is missing please let me know....

**Comment by jub3i** [comment]
@takirohit thanks!

**Comment by jub3i** [comment]
@takirohit I noticed a few things that where a little off in your PR after I merged it, so I made a few  changes at #438 - you can take a look at that if your interested.

**Pull request merged**
