### PR TITLE
let's fix links together

### PR DESCRIPTION
**Pull request by brettimus**
broken links are :scream_cat:

to that end, this tackles most of #511 - will rerun search for dead links once merged and live

### CODE REVIEW

**Comment by mikermcneil** [comment]
@brettimus this is exactly the kind of PR I've been hoping for re: the links.  Thanks so much!!!

**Comment by rachaelshaw** [comment]
:sob: This is beautiful.

**Comment by rachaelshaw** [comment]
(Especially thank you for escaping the parenthesis on wikipedia links.)

**Comment by brettimus** [comment]
awh shucks :flushed:

**Pull request merged**
