### PR TITLE
Made ja documents up-to-date

### PR DESCRIPTION
**Pull request by kory-yhg**
I finished with To0.10.md, and made documents up-to-date.
Now all files under concepts/ is translated and up-to-date as of Sep 27, 2015.

### CODE REVIEW

**Comment by hiroto-y** [comment]
I also made everything under getting-started up-to-date.

**Comment by kory-yhg** [comment]
Could someone merge this pull request? It has been open for 3 weeks.

**Comment by brettimus** [comment]
Ah! Sorry bout that. Will look it over shortly

**Comment by brettimus** [comment]
Well I can't check your translation :grin:, but looks good to me! Giving you the :+1: 

B

**Comment by brettimus** [comment]
Seriously @kory-yhg, really sorry this took so long. We appreciate you doing this work. It's not glorious, but it's incredibly helpful! You deserve a parade or something

**Comment by kory-yhg** [comment]
@brettimus, I finished with anatomy section as well, please merge #579.
And how should we working together on making sails-docs multilingual? #580

**Comment by brettimus** [comment]
Shit wait. I merged this in, but was the translation done on the original docs?

**Comment by brettimus** [comment]
Alright. Looked around a little bit, and it is making a little more sense to me. Could you still take me through how it works, though? Would be much appreciated.

**Comment by brettimus** [comment]
Then we can discuss how to coordinate in the future :relaxed:

**Comment by kory-yhg** [comment]
Thanks, @brettimus. btw, could you merge #579 as well.
This pull request is for anatomy section.

**Pull request merged**
