### PR TITLE
Update Assets.md

### PR DESCRIPTION
**Pull request by anibalmf1**
Translate to portuguese from the master/Assets.md

### CODE REVIEW

**Comment by brettimus** [comment]
obrigado! but sadly... nao falo? nao falo.

paging @marceloboeira and @gabrielalmir10 !

**Comment by anibalmf1** [comment]
Sorry, I haven't meant that. I meant that I have translated the master/Assets.md in this pull request.

**Comment by marceloboeira** [comment]
@anibalmf1 seem good enough. Thanks!

**Comment by brettimus** [comment]
On it!

**Pull request merged**
