### PR TITLE
Add SQL interface

### PR DESCRIPTION
**Pull request by dmarcelino**
Update adapter-specification.md to include the new SQL interface.
Details about this on: balderdashy/waterline-adapter-tests#40

### CODE REVIEW

**Comment by dmarcelino** [comment]
cc: @particlebanana, @tjwebb.

**Comment by particlebanana** [comment]
Looks good to me. Feel free to merge this if you are good with it @dmarcelino

**Comment by dmarcelino** [comment]
@particlebanana, I don't have permissions on sails-docs, so please do the honours! :wink:

**Comment by dmarcelino** [comment]
Thanks @jub3i!

**Pull request merged**
