### PR TITLE
Docs: Remove extra curly brace after if statement

### PR DESCRIPTION
**Pull request by abhisheksoni27**

### CODE REVIEW

**Comment by madisonhicks** [comment]
Thanks for your help, @abhisheksoni27 ! There _is_ actually an error in the code here, but that error is the lack of closing curly brace. The code should really look like this: 

```
// If no user was found, redirect to signup.
  if (!user) { 
     return res.redirect('/signup' );
  }
```
Do you want to go ahead and make that change? If not, I'm happy to do it.

**Comment by abhisheksoni27** [comment]
I'll do it.

**Comment by madisonhicks** [comment]
Good point! I think since we use the braces on all the other if statements, at least on that page, we'll probably want to include them here for consistency if nothing else.

**Comment by abhisheksoni27** [comment]
True. The examples should use the same set of coding style.

I've updated the code!

**Comment by madisonhicks** [comment]
Thanks so much!

**Comment by madisonhicks** [comment]
Confirmed and merged 🌊

**Comment by abhisheksoni27** [comment]
Awesome. Thanks!

**Pull request merged**
