### PR TITLE
updates waterline url

### PR DESCRIPTION
**Pull request by luislobo**
updates waterline url

### CODE REVIEW

**Comment by mikermcneil** [comment]
thanks!  If there are more like this, we can set up a hack in balderdashy/www.sailsjs.org to do a redirect rule

**Comment by mikermcneil** [comment]
(we're currently doing that for sails.io.js pages)

**Comment by mikermcneil** [comment]
but actually, it just occurred to me that we could just do this w/ cloudflare...  So I'll totally do that if it comes up.  So err... yeah let me know if you see anything like that!

**Comment by luislobo** [comment]
Ok! :)

**Pull request merged**
