### PR TITLE
Adding Status Code Parameter

### PR DESCRIPTION
**Pull request by KraFusion**
chaining status() and redirect() does not work, I believe the redirect defaults to 302 and overwrites whatever status is set in the status() part of the chain. Switching to the method documented in express works. This document will now match closer to what express has documented . https://expressjs.com/en/4x/api.html#res.redirect

### CODE REVIEW

**Comment by sgress454** [comment]
Thanks @KraFusion !

**Comment by mikermcneil** [comment]
@KraFusion Just to be clear, does `res.status(301).redirect('…')` not work?

**Comment by mikermcneil** [comment]
@KraFusion and if that's the case, then would you also resubmit this PR on the 1.0 branch?  Thanks a lot!

**Comment by sgress454** [comment]
@mikermcneil It definitely doesn't work!

**Comment by KraFusion** [comment]
@mikermcneil @sgress454 PR #943 has been submitted for the 1.0 branch.
I double checked that <code>res.status(301).redirect('…')</code> does indeed ignore the status code and sends a 302 instead.

**Pull request merged**
