### PR TITLE
PT-BR

### PR DESCRIPTION
**Pull request by anibalmf1**
Translation of the Blueprint Actions to portuguese

### CODE REVIEW

**Comment by anibalmf1** [comment]
@marceloboeira I've created the Blueprint folder in this pt-BR branch, just a pull from master.
For now, the only one translate file here is Blueprint Actions.md
As soon as possible I'll translate the others.

**Comment by marceloboeira** [comment]
@anibalmf1 thanks a lot! You have my OK! 

cc @brettimus

**Comment by rachaelshaw** [comment]
@anibalmf1 @marceloboeira sorry for taking so long to merge this!

**Comment by marceloboeira** [comment]
@rachaelshaw thanks 👍

**Pull request merged**
